### ISSUE TITLE
Flint is awesome.

### ISSUE THREAD

**Issue by etx** [JasonEtco/flintcms#55]
Just wanted to say this is a killer start on something that I've been wanting to work on / use for a long time. Craft is great for organizing content so it is a great inspiration for a Node based CMS. There is a huge void that Flint could fill. I can't stand PHP anymore. 

Looking forward to contributing where I can. Looks like you haven't made any commits in a while. Do you plan on continuing to work on Flint? 

Also, I couldn't figure out how to add a new admin account from the docs. After reviewing the source I found the post route to add a new admin and did it from Curl. 

I'm a Designer/Art director by day with a programming background so I can help with UX and design work as well.

**Comment by JasonEtco** [comment]
Thanks so much @etx ❤️! It means a ton that someone like you has both used it and enjoyed using it. I haven't been able to give Flint a lot of love recently, but messages like this are a great motivation!

> Looking forward to contributing where I can. Looks like you haven't made any commits in a while. Do you plan on continuing to work on Flint?

Absolutely yes, but I have a lot of plans for a lot of things. I've been spending most of my free time on [Probot](https://github.com/probot/probot) recently, and then there's work, and etc etc. But I really love the project and want to give it more time.

> Also, I couldn't figure out how to add a new admin account from the docs. After reviewing the source I found the post route to add a new admin and did it from Curl.

That's uuuh creative 😂 Sorry that it wasn't obvious. You _should_ be able to create a new user via the UI (`/admin/users/new`) and select the **Admin** usergroup. If you mean that you were having trouble creating the _first_ admin account, that should have been handled during the setup process.

> I'm a Designer/Art director by day with a programming background so I can help with UX and design work as well.

PRs are so, so welcome. Like I said, I've been strapped for time for Flint recently but I will always have time to review PRs. Feel free to open up issues for specific areas you want to tackle, and we can talk about it there! 💖

**Comment by etx** [comment]
I know what you mean about finding time. I work at a large digital marketing agency and time for projects like this is virtually non existent. That's probably why I never tackled something like this from scratch! 

I do however have a few weeks off work coming up. I'll be doing a new site for a small startup that would be a good use for flint.

Could do give me any info on how to setup the dev environment? I checked out the repo and sent the env but it's not clear how to build the admin UI. I'm not well versed in React. I used to use Angular and more recently move to using Vue.

**Comment by JasonEtco** [comment]
> I'll be doing a new site for a small startup that would be a good use for flint.

😍 

> Could do give me any info on how to setup the dev environment?

Sure thing! Here are the [CONTRIBUTING docs](https://github.com/JasonEtco/flintcms/blob/master/.github/CONTRIBUTING.md#getting-up-and-running), the admin UI builds if you have `BUILD_DASHBOARD` as `true`. You can also run:

```bash
$ npm run build
```

That will build the "production" UI. If you're working on the UI you'll probably want to go the first route, since it watches for changes and [hot reloads modules](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf)

**Comment by etx** [comment]
ahh missed that! Will check it out. Thanks, and Happy New year!

**Comment by etx** [comment]
> If you mean that you were having trouble creating the first admin account, that should have been handled during the setup process.

Is there something I missed in the docs on the setup process? Or was this overlooked in the docs? Willing to fix and send a PR if it's something that needs improvement.

**Comment by JasonEtco** [comment]
If you go to `/admin/install`, you should be prompted to setup the first admin user account. In looking at the docs, it does not appear that that's written anywhere - it should be, but you should also be directed there if no users exist yet when you go to `/admin`. If you'd like to make a PR that'd be awesome 💖

**Comment by etx** [comment]
Ah! That's the route! 

What do you think about me taking a try at building on new install on-boarding section. It could build out he .env settings through the web view and then finally setup the initial user. 

Looking for little things to do when I manage to find time. 🤓

**Comment by JasonEtco** [comment]
> What do you think about me taking a try at building on new install on-boarding section. 

Go for it! I think there's a lot of room for improvement there!

> It could build out he .env settings through the web view and then finally setup the initial user.

That's a really interesting idea. Currently, as the server starts up it connects to the database - that would have to be pushed back until this process has been completed and the db connection variables have been set. That might mean a lot of changes to the startup sequence.

Some of it is automatically generated already (the .env file as a whole, the `SESSION_SECRET`); maybe we can just point new installations to that file instead, as part of the onboarding flow?

**Comment by JasonEtco** [comment]
@etx I'm going to close this issue because there doesn't seem to be any pending action items; if you'd like to continue working on the onboarding flow we can take it from there ❤️
