### ISSUE TITLE
Dropdown field is breaking

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/flintcms#64]
The Dropdown field is throwing an error:

```
TypeError: sorted is undefined [index.js:50]
```

That's `components/Fields/Dropdown/index.js`.

**Comment by etx** [comment]
Looks like it's not receiving the correct options when being rendered through utils/renderOption.js

**Comment by JasonEtco** [comment]
I can't seem to reproduce this anymore, so I'm going to close this issue and hope its been fixed 🤞
