### ISSUE TITLE
DatePicker component not working as page field

### ISSUE THREAD

**Issue by etx** [JasonEtco/flintcms#66]
Looking into this one it seems that the date is saving as a string when being used as a page field. But the picker works fine in the aside when it is supplied a proper date date from the DB. 

I can get it to work by changing the value def in the DatePicker constructor() to:
`
const value = (props.defaultValue ? new Date(props.defaultValue).getTime() : props.value);
`
But I think this is more of a hack than a fix. You probably have a better idea how to normalize the data the field is receiving.

**Comment by JasonEtco** [comment]
Cool, thanks for the report, I'll look into it. It's been a while since I've dug into that code but I think it's just some discrepancies between the defaultValue and provided values.
