### ISSUE TITLE
node index.js in my command line returns nothing 

### ISSUE THREAD

**Issue by mariadada** [JasonEtco/flintcms#68]
Hi,

I just wanted to say that I love the idea behind flintcms.  I've just installed it and I'm trying to run the example code:

```
const Flint = require('flintcms');

const flintServer = new Flint({
  siteName: 'My Amazing Flint Site!'
});

flintServer.startServer();
```

But it's not working.  I get returned to the command line without any errors, nothing in the log.

Any ideas?

I'm running Mac Sierra 10.12.6
Node v9.6.1
npm v5.6.0

**Comment by JasonEtco** [comment]
Hey @mariadada! Sorry you're having problems 😭 I haven't done extensive testing, but I've noticed that many of the integration tests fail in Node `9.x`, so I'm thinking that's probably the culprit. Really glad you included version numbers, super helpful!

You can try downgrading to Node `8.9.4` (using [`nvm`](https://github.com/creationix/nvm) is the way to go). Let me know if that works for you - I'd love to support `9.x`, but I'm a little strapped for time to work on that 😁

**Comment by mariadada** [comment]
Hi Jason.


I tried downgrading node to 8.9.4 but I'm still getting the same problem.  Any ideas? I'm included a screenshot of nvm

________________________________

**Comment by JasonEtco** [comment]
Darn, I hoped that would work! Ok; can you share a bit more about your setup? Ideally, your directory would look something like:

```
/
├── index.js
├── node_modules
└── package.json
```

And after installing the dependencies (`npm install`) running `node index.js` while inside that directory would run the server. To verify, you can add this to the top of your `index.js` file:

```js
console.log('I am running!')
```

And lastly, juuuust to be certain (because `nvm` can be tricky), can you run `node --version` just before you run `node index.js`? That way we can be certain of which version of Node is actually being used.

**Comment by fornof** [comment]
I am also having the same issue. here is what I am trying with commands:  
node -v : v8.0.0
nvm use 8.0 : Now using node v8.0.0 (npm v5.0.0)
npm install flintcms, I get:  
MyPc:my-project rob$ npm install flintcms
npm WARN saveError ENOENT: no such file or directory, open '/Users/rob/Projects/web/my-project/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/rob/Projects/web/my-project/package.json'
npm WARN my-project No description
npm WARN my-project No repository field.
npm WARN my-project No README data
npm WARN my-project No license field.


my indexcopy.js is attached. 
[indexcopy.txt](https://github.com/JasonEtco/flintcms/files/1831849/indexcopy.txt)

node index.js , I get:  hey it's flint!

**Comment by JasonEtco** [comment]
@fornof your issue is different - this is a common error around using NPM modules. In the future, I recommend you Google such error messages, you'll likely find help faster!

In the meantime, your project is missing a `package.json` file, which is how NPM keeps track of what libraries your project uses. You can use the `npm init` command to scaffold a `package.json` file for you. Here are their docs: https://docs.npmjs.com/cli/init

**Comment by JasonEtco** [comment]
Please make sure that you've followed all of the [instructions on the installation page](https://flintcms.co/docs/installation/). I think you're missing some required credentials in your `.env` file, specifically your database host `DB_HOST`.

If you're on a Mac, try running:

```
DEBUG=flint node index.js
```

Or adding this to the top of your `index.js` file:

```js
process.env.DEBUG = 'flint'
```

**Comment by fornof** [comment]
I setup mailgun and mongodb, and enabled debugging. I see a "flint [HTTP Server] Flint server running at http://localhost:4000" , and it asks for a username and password. 

I don't know where Settings / Sites Settings are , maybe admin ?  "under Settings/Site Settings) you can enable or disable the endpoints that allow for form or AJAX inputs
https://flintcms.co/docs/users/

How do I sign in or add a user? It looks like mongodb has an admin.users table.

**Comment by matthewmorek** [comment]
@fornof Yeah, the docs weren't clear on this. After bootstrapping and running FlintCMS, you can access it from default url: http://localhost:4000.

- Installation can be started from: http://localhost:4000/admin/install (do this first)
- Admin UI is accessible from: http://localhost:4000/admin

I hope that helps. I'll be sure to update the docs to mention that quite crucial info.

**Comment by matthewmorek** [comment]
I'd vote to close this issue, as we seem to have collectively resolve it with a mix of debugging tips and documentation updates.

**Comment by JasonEtco** [comment]
Agreed. Thanks all for the comments and suggestions. If you're still having trouble, feel free to reopen this issue.
