### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [JasonEtco/flintcms#77]
Hello,

As a member of the [Node.js Security WG](https://hackerone.com/nodejs-ecosystem)
I would like to draw your attention to a security report that has been made regarding this issue.

I have made attempts to contact the person identified as a maintainer of this package but did not get any answer. What is the best way to reach someone with commit rights over this repo and hopefully npm publishing rights as well, in order to invite them to privately discuss the issue on the HackerOne platform and provide a resolution? 

Thanks,
Liran.

References:
* [Node.js Security WG ecosystem vulnerability processes](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md)

**Comment by JasonEtco** [comment]
Hey Liran,

You can contact me directly at `jasonetco at github dot com`.

**Comment by lirantal** [comment]
I sent you a second invite now to that address.
Maybe check your spam folder too if you don't see it.

Thanks for the prompt reply!
